### ISSUE TITLE
Zulip api doesn't work with python 3.8

### ISSUE THREAD

**Issue by janLo** [zulip/python-zulip-api#530]
Using the zulip api on a current python 3.8 causes an `AttributeError` because of the removal of `linux_distribution` from `platform`:
```
AttributeError: module 'platform' has no attribute 'linux_distribution'
[...]
  File "__init__.py", line 1007, in get_profile
    return self.call_endpoint(
  File "__init__.py", line 623, in call_endpoint
    return self.do_api_query(marshalled_request, versioned_url, method=method,
  File "__init__.py", line 505, in do_api_query
    self.ensure_session()
  File "__init__.py", line 450, in ensure_session
    session.headers.update({"User-agent": self.get_user_agent()})
  File "__init__.py", line 466, in get_user_agent
    vendor, vendor_version, dummy = platform.linux_distribution()
```
See https://bugs.python.org/issue28167 and https://github.com/pypa/pip/pull/3906/files for a possible workaround.

**Comment by janLo** [comment]
Oh, I've just seen 63bc9b8a4fe922befac8c8b0000d30b22911d797. Can this be released soon?

**Comment by neiljp** [comment]
@janLo There has been discussion on releasing a new version over the last month, on the #integrations stream at chat.zulip.org.

@eeshangarg FYI :)

**Comment by mikaelmello** [comment]
Additionally, I am getting errors because of `typed-ast`: https://github.com/python/typed_ast/issues/126

**Comment by neiljp** [comment]
@janLo Can you clarify whether this works for you at this point?

@mikaelmello Thanks for the link; to clarify, is this just an upstream problem as per the one you point to, (which seems fixed), or are you seeing it with a zulip dev environment?

**Comment by mikaelmello** [comment]
Hi Neil, this is an upstream problem that was present when I was trying to
setup my environment. I've managed to fix it by bumping the version of the
dependency.

Em qua, 1 de jan de 2020 21:17, Neil Pilgrim <notifications@github.com>
escreveu:

**Comment by eeshangarg** [comment]
@mikaelmello Thanks for the response! @neiljp I'm guessing we can close this one then?

**Comment by timabbott** [comment]
I think that's correct, closing.
